krakend/krakend-jose

- Gopkg.lock
- Gopkg.toml
- jose.go
- jose_example_test.go
- jwk.go
- jwk_test.go
- jws.go
- jws_test.go
As requested in #4, this PR restricts the collection of supported cipher suites.
> restrict cipher suites supported by the jwk http client

- jose_example_test.go
- jose_test.go
- jws.go
- jws_test.go
Instead of throwing a warning as suggested at #6 , this PR introduces a new param `disable_jwk_security` at both config types - signer and verifier - so the config parsers will return an error if the URL of the JWK service is not HTTPS and the JWK Security has not been disabled at the configuration
> JWK clients should use HTTPS

- jose.go
- jwk.go
- jwk_example_test.go
- jwk_test.go
- jws.go
- jws_test.go
as requested in #3 , this PR adds support for public key pinning for the JWK client.
The feature is enabled if one or more key fingerprints are added to the endpoint configs
> Add support for Public Key Pinning

- .gitignore
- Makefile
- jose.go
- jwk.go
- jwk_test.go
- jws.go
- jws_test.go
this PR introduces a new config param `jwk_local_ca` for the verifier and signer middlewares so users can use certs not included into the system CA with the JWK client
> support for local CA added

- gin/jose.go
- mux/jose.go
- rejecter.go
so rejecters can be created based on the endpoint configuration
> rejecter factory added

- gin/jose.go
- jose.go
- jose_test.go
- mux/jose.go
scan substructs when looking for the set of roles if the role key contains a '.' as requested at https://github.com/devopsfaith/krakend-ce/issues/146
> Roles nested in properties

- jwk.go
- jws.go
- jws_test.go
This PR is just adds cacheDuration parameter. When specified, the default value (15 minutes) is replaced.
> Resolve: Add option to configure key caching duration (#24)

- jwk.go
- jwk_test.go
force an initial key request so the SecretProvider's cache gets initialized before starting the service
> JWK cache initialized

- gin/jose.go
- gin/jose_example_test.go
- gin/jose_test.go
- jose.go
- jws.go
- mux/jose.go
- mux/jose_example_test.go
- mux/jose_test.go
This pull request enables the functionality to forward claims in a JWT as request headers. It is a common use case to e.g. have the `sub` claim added as a `X-User` header to the request. This can be enabled by this PR. I added a new configuration option to the krakend-jose component ("propagate-claims") which takes an array of "claim/header" values, describing how to map which claim to which header value. Sample:
```json
"extra_config": {
"github.com/devopsfaith/krakend-jose/validator": {
...
...
"propagate-claims": [
["sub", "x-user"]
]
...
...
}
},
```
In this case, the value of the `sub` claim will be added as `x-user` header to the request. If the claim does not exists, the mapping is just skipped.
Tests have been added.
Important: to have the headers forwarded to the backend, you …
> Add ability to propagate JWT claims as request headers

- gin/jose.go
- jose.go
- jose_test.go
- jws.go
- mux/jose.go
This PR adds the ability to validate scopes in a JWT token. The key for the scopes claim can be customized ("scopes_key" property) and the value can be read from a nested property in the token (same as for "role" validation). Additionally, the matching function can be customized: "any" returns "true" when at least one of the required scopes is available in the token, "all" means that all required scopes need to be included.
If the validation fails, a 403 will be returned.
Tests have been added.
> Add JWT scopes validation

- gin/jose.go
- gin/jose_example_test.go
- gin/jose_test.go
- mux/jose.go
- mux/jose_example_test.go
- mux/jose_test.go
When propagating JWT claims to header values, replace values from
headers that already exist instead of appending the claims.
Fixes #62
> JWT/header propagation: replace existing values

- jose.go
Given a JWT like
```json
{
"sub": "1234567890",
"name": "John Doe",
"iat": 1516239022,
"customClaim": {
"nested": "value"
}
}
```
then this PR allows the propagation of a nested claim to a header using dot notation, like
```json
"github.com/devopsfaith/krakend-jose/validator": {
"propagate-claims": [
["customClaim.nested", "X-Nested-Claim"]
]
}
```
> Allow the propagation of nested claims using dot notation

- jwk.go
- key_cacher.go
copy the key before adding it to the key mapper, so the latter doesn't override all the other entries
> Fix the file key cacher constructor

- go.mod
- go.sum
- jose.go
- jose_test.go
this PR fixes the bug reported at https://github.com/devopsfaith/krakend-jose/pull/85#issuecomment-1113550033 by @lwohlhart
Important details:
- floats with very small distances (epsilon <= 1e-6) from their `math.Round` equivalent are replaced by the rounded value.
- big integers are kept as integers and are not converter to their exponential/engineering representation
> Fix float normalization

- jwk.go
**Why**: When using the `jwk_local_path` parameter with `cache` enabled, unexpected behavior occurs: jose tries to use an empty jwk_url variable. Еhere is no error or warning in the logs, which makes it quite difficult to understand source of the problem
> jwk_local_path with cache

- jwk.go
- jwk_client_test.go
- key_cacher.go
to reduce pressure on the JWK backends.
> Add a global cache layer common for all the endpoints

- jose.go
- jose_test.go
Fix index out of range [0] with length 0 when passing a claim that contains an empty list. Issue https://github.com/krakendio/krakend-jose/issues/115
> Fix index out of range

- jose.go
- jose_test.go
This is re-opening an [older PR](https://github.com/krakend/krakend-jose/pull/84) by [xiaofei-du](https://github.com/xiaofei-du)
**Why**
When validating the JWT token, the original [krakend-jose](https://www.krakend.io/docs/authorization/jwt-validation/) only supports space-delimited scopes, e.g:
```
{
...
"my_scopes": "scope1 scope2"
}
```
This PR makes krakend-jose also support scope list in JWT token , e.g:
```
{
...
"my_scopes": ["scope1", "scope2"]
}
```
This makes krakend compatible with third party providers using this format.
> feat: support for scope list in JWT token for scope validation

- jose.go
- jwk_client.go
Need to expose functions without a dependency on the `http` package to validate JWT
> Support non HTTP JWT validation

- jwk_client.go
- key_cacher.go
Added `x5t#S256` as [key identification strategy ](https://www.krakend.io/docs/authorization/jwt-validation/)
Token header example, only with `x5t#S256, which was not able to identify before and failed:
```
{
"alg": "HS256",
"typ": "JWT",
"x5t#s256": "tupu"
}
```
> Add support for x5t#S256 key identification
